// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/orderbook.proto

package orderbookpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderbookService_RegisterMatch_FullMethodName = "/orderbook.OrderbookService/RegisterMatch"
)

// OrderbookServiceClient is the client API for OrderbookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderbookServiceClient interface {
	RegisterMatch(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*RegisterMatchResponse, error)
}

type orderbookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderbookServiceClient(cc grpc.ClientConnInterface) OrderbookServiceClient {
	return &orderbookServiceClient{cc}
}

func (c *orderbookServiceClient) RegisterMatch(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*RegisterMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterMatchResponse)
	err := c.cc.Invoke(ctx, OrderbookService_RegisterMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderbookServiceServer is the server API for OrderbookService service.
// All implementations must embed UnimplementedOrderbookServiceServer
// for forward compatibility.
type OrderbookServiceServer interface {
	RegisterMatch(context.Context, *MatchRequest) (*RegisterMatchResponse, error)
	mustEmbedUnimplementedOrderbookServiceServer()
}

// UnimplementedOrderbookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderbookServiceServer struct{}

func (UnimplementedOrderbookServiceServer) RegisterMatch(context.Context, *MatchRequest) (*RegisterMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMatch not implemented")
}
func (UnimplementedOrderbookServiceServer) mustEmbedUnimplementedOrderbookServiceServer() {}
func (UnimplementedOrderbookServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderbookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderbookServiceServer will
// result in compilation errors.
type UnsafeOrderbookServiceServer interface {
	mustEmbedUnimplementedOrderbookServiceServer()
}

func RegisterOrderbookServiceServer(s grpc.ServiceRegistrar, srv OrderbookServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderbookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderbookService_ServiceDesc, srv)
}

func _OrderbookService_RegisterMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderbookServiceServer).RegisterMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderbookService_RegisterMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderbookServiceServer).RegisterMatch(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderbookService_ServiceDesc is the grpc.ServiceDesc for OrderbookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderbookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbook.OrderbookService",
	HandlerType: (*OrderbookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMatch",
			Handler:    _OrderbookService_RegisterMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orderbook.proto",
}
