// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/orderbook.proto

package orderbookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TeamA         string                 `protobuf:"bytes,2,opt,name=team_a,json=teamA,proto3" json:"team_a,omitempty"`
	TeamB         string                 `protobuf:"bytes,3,opt,name=team_b,json=teamB,proto3" json:"team_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchRequest) GetTeamA() string {
	if x != nil {
		return x.TeamA
	}
	return ""
}

func (x *MatchRequest) GetTeamB() string {
	if x != nil {
		return x.TeamB
	}
	return ""
}

type RegisterMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMatchResponse) Reset() {
	*x = RegisterMatchResponse{}
	mi := &file_proto_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMatchResponse) ProtoMessage() {}

func (x *RegisterMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMatchResponse.ProtoReflect.Descriptor instead.
func (*RegisterMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_orderbook_proto protoreflect.FileDescriptor

const file_proto_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x15proto/orderbook.proto\x12\torderbook\"W\n" +
	"\fMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x15\n" +
	"\x06team_a\x18\x02 \x01(\tR\x05teamA\x12\x15\n" +
	"\x06team_b\x18\x03 \x01(\tR\x05teamB\"/\n" +
	"\x15RegisterMatchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2^\n" +
	"\x10OrderbookService\x12J\n" +
	"\rRegisterMatch\x12\x17.orderbook.MatchRequest\x1a .orderbook.RegisterMatchResponseB-Z+github.com/amithshubhan/Bet_Now/orderbookpbb\x06proto3"

var (
	file_proto_orderbook_proto_rawDescOnce sync.Once
	file_proto_orderbook_proto_rawDescData []byte
)

func file_proto_orderbook_proto_rawDescGZIP() []byte {
	file_proto_orderbook_proto_rawDescOnce.Do(func() {
		file_proto_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderbook_proto_rawDesc), len(file_proto_orderbook_proto_rawDesc)))
	})
	return file_proto_orderbook_proto_rawDescData
}

var file_proto_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_orderbook_proto_goTypes = []any{
	(*MatchRequest)(nil),          // 0: orderbook.MatchRequest
	(*RegisterMatchResponse)(nil), // 1: orderbook.RegisterMatchResponse
}
var file_proto_orderbook_proto_depIdxs = []int32{
	0, // 0: orderbook.OrderbookService.RegisterMatch:input_type -> orderbook.MatchRequest
	1, // 1: orderbook.OrderbookService.RegisterMatch:output_type -> orderbook.RegisterMatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orderbook_proto_init() }
func file_proto_orderbook_proto_init() {
	if File_proto_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderbook_proto_rawDesc), len(file_proto_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderbook_proto_goTypes,
		DependencyIndexes: file_proto_orderbook_proto_depIdxs,
		MessageInfos:      file_proto_orderbook_proto_msgTypes,
	}.Build()
	File_proto_orderbook_proto = out.File
	file_proto_orderbook_proto_goTypes = nil
	file_proto_orderbook_proto_depIdxs = nil
}
